### ISSUE TITLE
Docker with docker-compose.yml is not woriking

### ISSUE THREAD

**Issue by Proxyyy87** [invoicerr-app/invoicerr#228]
**Describe the bug**
with the file [docker-compose.yml](https://github.com/Impre-visible/invoicerr/blob/main/docker-compose.yml) it try to install the docker but its not working.

**To Reproduce**
use the file

The following is shown in the log:
`npm warn exec The following package was not found and will be installed: prisma@7.0.1

! unknown or unexpected option: --skip-generate

🙌  Push the state from your Prisma schema to your database

Usage

  $ prisma db push [options]

  The datasource URL configuration is read from the Prisma config file (e.g., prisma.config.ts).

Options

           -h, --help   Display this help message

             --config   Custom path to your Prisma config file

             --schema   Custom path to your Prisma schema

   --accept-data-loss   Ignore data loss warnings

        --force-reset   Force a reset of the database before push

Examples

  Push the Prisma schema state to the database

  $ prisma db push

  Specify a schema

  $ prisma db push --schema=./schema.prisma

  Ignore data loss warnings

  $ prisma db push --accept-data-loss

npm notice

npm notice New major version of npm available! 10.9.2 -> 11.6.4

npm notice Changelog: https://github.com/npm/cli/releases/tag/v11.6.4

npm notice To update run: npm install -g npm@11.6.4

npm notice

Waiting for backend to start...

node:internal/modules/cjs/loader:1247


  throw err;

  ^

Error: Cannot find module '/usr/share/nginx/backend/main.js'

    at Function._resolveFilename (node:internal/modules/cjs/loader:1244:15)

    at Function._load (node:internal/modules/cjs/loader:1070:27)

    at TracingChannel.traceSync (node:diagnostics_channel:322:14)

    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)

    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:170:5)

    at node:internal/main/run_main_module:36:49 {

  code: 'MODULE_NOT_FOUND',

  requireStack: []

}

Node.js v22.13.1`

i use the latest file v1.3.3.b

**Comment by Impre-visible** [comment]
Hi, thanks for the ticket, a strange thing is that this should be resolved...

Prisma made breaking changes in the v7 so we must use specific versions, and in your case it's not working... I'll take a look at it asap

**Comment by jpurdy647** [comment]
Same issue, thanks for your work! Will try an install again soon

**Comment by sbcrumb** [comment]
Running into this issue as well on a new install.

**Comment by Impre-visible** [comment]
I opened an issue (#231) to work on the migration to prisma v7

**Comment by Impre-visible** [comment]
Hi, I invite you to try the version `v1.4.0i` that should solve the issue for good. Let me know if there's new issues

@sbcrumb @jpurdy647 @Proxyyy87

**Comment by Proxyyy87** [comment]
Hi,
i tested the new version. But still the same issue what i got with the new docker-compose.yml.
Here is the log file. Also the postgresql is with an error, i add the log as well.

[_invoicerr-invoicerr_db-1_logs.txt](https://github.com/user-attachments/files/23997734/_invoicerr-invoicerr_db-1_logs.txt)
[_invoicerr-invoicerr-1_logs.txt](https://github.com/user-attachments/files/23997733/_invoicerr-invoicerr-1_logs.txt)

**Comment by Impre-visible** [comment]
Oh, the logs are clear, you updated the version of Postgres to 17, but the data of the container is for 15... either you change the version to the 15, or you reset your database container.

**Comment by Proxyyy87** [comment]
Ok for the database issue its easy to fix i changed it back to 15. But you did the version change in the compose file

  invoicerr_db:
    image: **postgres:17**
    environment:
      POSTGRES_USER: invoicerr
      POSTGRES_PASSWORD: invoicerr
      POSTGRES_DB: invoicerr_db
    volumes:
      - db_data:/var/lib/postgresql/data

with this the creation is not working.

i create both as stack in portainer. so the docker-compose does everything for me.

**Comment by Impre-visible** [comment]
I'm sorry @Proxyyy87 but it works fine on my end. What's your achitecture ? Did you tried to remove the db_data volume?

**Comment by sbcrumb** [comment]
@Impre-visible  I removed the docker database volume I pulled the latest image(unless I Need to specify a version) and the same error happens. this is a brand new install so I have nothing setup etc.

```
docker compose up
[+] Running 4/4
 ✔ Network invoicerr_default           Created                                                                                                                                                                                                         0.0s
 ✔ Volume invoicerr_db_data            Created                                                                                                                                                                                                         0.0s
 ✔ Container invoicerr-invoicerr_db-1  Created                                                                                                                                                                                                         0.1s
 ✔ Container invoicerr-invoicerr-1     Created                                                                                                                                                                                                         0.1s
Attaching to invoicerr-1, invoicerr_db-1
invoicerr_db-1  | The files belonging to this database system will be owned by user "postgres".
invoicerr_db-1  | This user must also own the server process.
invoicerr_db-1  |
invoicerr_db-1  | The database cluster will be initialized with locale "en_US.utf8".
invoicerr_db-1  | The default database encoding has accordingly been set to "UTF8".
invoicerr_db-1  | The default text search configuration will be set to "english".
invoicerr_db-1  |
invoicerr_db-1  | Data page checksums are disabled.
invoicerr_db-1  |
invoicerr_db-1  | fixing permissions on existing directory /var/lib/postgresql/data ... ok
invoicerr_db-1  | creating subdirectories ... ok
invoicerr_db-1  | selecting dynamic shared memory implementation ... posix
invoicerr_db-1  | selecting default "max_connections" ... 100
invoicerr_db-1  | selecting default "shared_buffers" ... 128MB
invoicerr_db-1  | selecting default time zone ... Etc/UTC
invoicerr_db-1  | creating configuration files ... ok
invoicerr_db-1  | running bootstrap script ... ok
invoicerr_db-1  | performing post-bootstrap initialization ... ok
invoicerr_db-1  | initdb: warning: enabling "trust" authentication for local connections
invoicerr_db-1  | initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
invoicerr_db-1  | syncing data to disk ... ok
invoicerr_db-1  |
invoicerr_db-1  |
invoicerr_db-1  | Success. You can now start the database server using:
invoicerr_db-1  |
invoicerr_db-1  |     pg_ctl -D /var/lib/postgresql/data -l logfile start
invoicerr_db-1  |
invoicerr_db-1  | waiting for server to start....2025-12-09 20:00:11.881 UTC [49] LOG:  starting PostgreSQL 17.7 (Debian 17.7-3.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit
invoicerr_db-1  | 2025-12-09 20:00:11.882 UTC [49] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
invoicerr_db-1  | 2025-12-09 20:00:11.885 UTC [52] LOG:  database system was shut down at 2025-12-09 20:00:11 UTC
invoicerr_db-1  | 2025-12-09 20:00:11.889 UTC [49] LOG:  database system is ready to accept connections
invoicerr_db-1  |  done
invoicerr_db-1  | server started
invoicerr_db-1  | CREATE DATABASE
invoicerr_db-1  |
invoicerr_db-1  |
invoicerr_db-1  | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
invoicerr_db-1  |
invoicerr_db-1  | waiting for server to shut down....2025-12-09 20:00:12.049 UTC [49] LOG:  received fast shutdown request
invoicerr_db-1  | 2025-12-09 20:00:12.051 UTC [49] LOG:  aborting any active transactions
invoicerr_db-1  | 2025-12-09 20:00:12.052 UTC [49] LOG:  background worker "logical replication launcher" (PID 55) exited with exit code 1
invoicerr_db-1  | 2025-12-09 20:00:12.053 UTC [50] LOG:  shutting down
invoicerr_db-1  | 2025-12-09 20:00:12.054 UTC [50] LOG:  checkpoint starting: shutdown immediate
invoicerr_db-1  | 2025-12-09 20:00:12.087 UTC [50] LOG:  checkpoint complete: wrote 925 buffers (5.6%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.017 s, sync=0.014 s, total=0.034 s; sync files=301, longest=0.002 s, average=0.001 s; distance=4256 kB, estimate=4256 kB; lsn=0/1915968, redo lsn=0/1915968
invoicerr_db-1  | 2025-12-09 20:00:12.091 UTC [49] LOG:  database system is shut down
invoicerr_db-1  |  done
invoicerr_db-1  | server stopped
invoicerr_db-1  |
invoicerr_db-1  | PostgreSQL init process complete; ready for start up.
invoicerr_db-1  |
invoicerr_db-1  | 2025-12-09 20:00:12.163 UTC [1] LOG:  starting PostgreSQL 17.7 (Debian 17.7-3.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit
invoicerr_db-1  | 2025-12-09 20:00:12.163 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
invoicerr_db-1  | 2025-12-09 20:00:12.163 UTC [1] LOG:  listening on IPv6 address "::", port 5432
invoicerr_db-1  | 2025-12-09 20:00:12.166 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
invoicerr_db-1  | 2025-12-09 20:00:12.169 UTC [65] LOG:  database system was shut down at 2025-12-09 20:00:12 UTC
invoicerr_db-1  | 2025-12-09 20:00:12.172 UTC [1] LOG:  database system is ready to accept connections
invoicerr-1     | npm warn exec The following package was not found and will be installed: prisma@7.1.0
invoicerr-1     |
invoicerr-1     | ! unknown or unexpected option: --skip-generate
invoicerr-1     |
invoicerr-1     | 🙌  Push the state from your Prisma schema to your database
invoicerr-1     |
invoicerr-1     | Usage
invoicerr-1     |
invoicerr-1     |   $ prisma db push [options]
invoicerr-1     |
invoicerr-1     |   The datasource URL configuration is read from the Prisma config file (e.g., prisma.config.ts).
invoicerr-1     |
invoicerr-1     | Options
invoicerr-1     |
invoicerr-1     |            -h, --help   Display this help message
invoicerr-1     |              --config   Custom path to your Prisma config file
invoicerr-1     |              --schema   Custom path to your Prisma schema
invoicerr-1     |    --accept-data-loss   Ignore data loss warnings
invoicerr-1     |         --force-reset   Force a reset of the database before push
invoicerr-1     |
invoicerr-1     | Examples
invoicerr-1     |
invoicerr-1     |   Push the Prisma schema state to the database
invoicerr-1     |   $ prisma db push
invoicerr-1     |
invoicerr-1     |   Specify a schema
invoicerr-1     |   $ prisma db push --schema=./schema.prisma
invoicerr-1     |
invoicerr-1     |   Ignore data loss warnings
invoicerr-1     |   $ prisma db push --accept-data-loss
invoicerr-1     |
invoicerr-1     | npm notice
invoicerr-1     | npm notice New major version of npm available! 10.9.2 -> 11.7.0
invoicerr-1     | npm notice Changelog: https://github.com/npm/cli/releases/tag/v11.7.0
invoicerr-1     | npm notice To update run: npm install -g npm@11.7.0
invoicerr-1     | npm notice
invoicerr-1     | Waiting for backend to start...
invoicerr-1     | node:internal/modules/cjs/loader:1247
invoicerr-1     |   throw err;
invoicerr-1     |   ^
invoicerr-1     |
invoicerr-1     | Error: Cannot find module '/usr/share/nginx/backend/main.js'
invoicerr-1     |     at Function._resolveFilename (node:internal/modules/cjs/loader:1244:15)
invoicerr-1     |     at Function._load (node:internal/modules/cjs/loader:1070:27)
invoicerr-1     |     at TracingChannel.traceSync (node:diagnostics_channel:322:14)
invoicerr-1     |     at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
invoicerr-1     |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:170:5)
invoicerr-1     |     at node:internal/main/run_main_module:36:49 {
invoicerr-1     |   code: 'MODULE_NOT_FOUND',
invoicerr-1     |   requireStack: []
invoicerr-1     | }
invoicerr-1     |
invoicerr-1     | Node.js v22.13.1
```

**Comment by Impre-visible** [comment]
Ok, I updated the postgres version to the 15, that should work for everyone now

**Comment by Hopeman876** [comment]
Hi guys,

I'm also facing this issue. I tried the mentioned image v1.4.0i and in this case the setup is working. But if I use the actual image, I receive those log entries:

```
 2026-01-05T10:45:28.748233601Z npm warn exec The following package was not found and will be installed: prisma@7.2.0
2026-01-05T10:45:47.037101938Z 
2026-01-05T10:45:47.037476871Z ! unknown or unexpected option: --skip-generate
2026-01-05T10:45:47.037530018Z 
2026-01-05T10:45:47.037559676Z 🙌  Push the state from your Prisma schema to your database
2026-01-05T10:45:47.037600787Z 
2026-01-05T10:45:47.037625011Z Usage
2026-01-05T10:45:47.037650499Z 
2026-01-05T10:45:47.037673356Z   $ prisma db push [options]
2026-01-05T10:45:47.037723744Z 
2026-01-05T10:45:47.037749199Z   The datasource URL configuration is read from the Prisma config file (e.g., prisma.config.ts).
2026-01-05T10:45:47.037786697Z 
2026-01-05T10:45:47.037809419Z Options
2026-01-05T10:45:47.037833447Z 
2026-01-05T10:45:47.037856847Z            -h, --help   Display this help message
2026-01-05T10:45:47.037887473Z              --config   Custom path to your Prisma config file
2026-01-05T10:45:47.037921279Z              --schema   Custom path to your Prisma schema
2026-01-05T10:45:47.037947974Z                  --url   Override the datasource URL from the Prisma config file
2026-01-05T10:45:47.037977192Z    --accept-data-loss   Ignore data loss warnings
2026-01-05T10:45:47.038005134Z         --force-reset   Force a reset of the database before push
2026-01-05T10:45:47.038034211Z 
2026-01-05T10:45:47.038056352Z Examples
2026-01-05T10:45:47.038082556Z 
2026-01-05T10:45:47.038104604Z   Push the Prisma schema state to the database
2026-01-05T10:45:47.038135848Z   $ prisma db push
2026-01-05T10:45:47.038159815Z 
2026-01-05T10:45:47.038181348Z   Specify a schema
2026-01-05T10:45:47.038206840Z   $ prisma db push --schema=./schema.prisma
2026-01-05T10:45:47.038236600Z 
2026-01-05T10:45:47.038258520Z   Ignore data loss warnings
2026-01-05T10:45:47.038282916Z   $ prisma db push --accept-data-loss
2026-01-05T10:45:47.038307729Z 
2026-01-05T10:45:47.065466667Z npm notice
2026-01-05T10:45:47.065598164Z npm notice New major version of npm available! 10.9.2 -> 11.7.0
2026-01-05T10:45:47.065640684Z npm notice Changelog: https://github.com/npm/cli/releases/tag/v11.7.0
2026-01-05T10:45:47.065704880Z npm notice To update run: npm install -g npm@11.7.0
2026-01-05T10:45:47.065741221Z npm notice
2026-01-05T10:45:47.154188165Z Waiting for backend to start...
2026-01-05T10:45:47.260791130Z node:internal/modules/cjs/loader:1247
2026-01-05T10:45:47.260932481Z   throw err;
2026-01-05T10:45:47.260964407Z   ^
2026-01-05T10:45:47.260988026Z 
2026-01-05T10:45:47.261010965Z Error: Cannot find module '/usr/share/nginx/backend/main.js'
2026-01-05T10:45:47.261044384Z     at Function._resolveFilename (node:internal/modules/cjs/loader:1244:15)
2026-01-05T10:45:47.261075669Z     at Function._load (node:internal/modules/cjs/loader:1070:27)
2026-01-05T10:45:47.261105882Z     at TracingChannel.traceSync (node:diagnostics_channel:322:14)
2026-01-05T10:45:47.261134486Z     at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
2026-01-05T10:45:47.261168540Z     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:170:5)
2026-01-05T10:45:47.261199756Z     at node:internal/main/run_main_module:36:49 {
2026-01-05T10:45:47.261227271Z   code: 'MODULE_NOT_FOUND',
2026-01-05T10:45:47.261252350Z   requireStack: []
2026-01-05T10:45:47.261278085Z }
2026-01-05T10:45:47.261358183Z 
2026-01-05T10:45:47.261383499Z Node.js v22.13.1
```

Before I started a new test, I've removed the file structur from my container folder. I changed also the postgres version from 17 to 15, but without success.
I'm running the container via portainer on my Synology NAS and for the installation I've followed the [installation guide from mariushosting.com](https://mariushosting.com/how-to-install-invoicerr-on-your-synology-nas/)


Best regards and thanks for your support in advance.

**Comment by Impre-visible** [comment]
Hi everyone... Sorry for the inconvenience that should be working fine. I'll try to take a look today at how I can fix that, the main issue is the fact that it works well on my end... I'll come back as soon as I have more information.

**Comment by Hopeman876** [comment]
> Hi everyone... Sorry for the inconvenience that should be working fine. I'll try to take a look today at how I can fix that, the main issue is the fact that it works well on my end... I'll come back as soon as I have more information.

Can I support you with any kind of logfiles or other stuff?

**Comment by Impre-visible** [comment]
> > Hi everyone... Sorry for the inconvenience that should be working fine. I'll try to take a look today at how I can fix that, the main issue is the fact that it works well on my end... I'll come back as soon as I have more information.
> 
> Can I support you with any kind of logfiles or other stuff?

Can you provide me with your current docker-file please? So I try the same on my side. Thanks

**Comment by Hopeman876** [comment]
You mean the compse content for the portainer stack? If yes, you'll find bellow; I've just cleared my personal information and mail password.

```
services:
  db:
    image: postgres:15
    container_name: Invoicerr-DB
    hostname: invoicerr-db
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "invoicerr", "-U", "invoicerruser"]
      timeout: 45s
      interval: 10s
      retries: 10
    volumes:
      - /volume1/docker/invoicerrdb:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_DB: invoicerr
      POSTGRES_USER: invoicerruser
      POSTGRES_PASSWORD: invoicerrpass
    restart: on-failure:5

  invoicerr:
    #image: ghcr.io/impre-visible/invoicerr:v1.4.0i
    image: ghcr.io/impre-visible/invoicerr:latest
    container_name: Invoicerr
    hostname: invoicerr
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: timeout 10s bash -c ':> /dev/tcp/127.0.0.1/80' || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s  
    ports:
      - 7913:80
    environment:
      DATABASE_URL: postgresql://invoicerruser:invoicerrpass@invoicerr-db:5432/invoicerr
      APP_URL: ClearedForGithub
      CORS_ORIGINS: ClearedForGithub
      JWT_SECRET: KDdDqDftQegyDavAFpjxPdgUZUWABvEwHCPBDUhTWtzTXltQuyQCibpqHmtSvrTi
      SMTP_HOST: posteo.de
      SMTP_USER: ClearedForGithub
      SMTP_FROM: ClearedForGithub
      SMTP_PORT: 587
      SMTP_PASSWORD: ClearedForGithub
    restart: on-failure:5
    depends_on:
      db:
        condition: service_healthy
```
